apiVersion: v1
kind: Pod
metadata:
  labels:
    run: curl
  name: curl
spec:
  containers:
    - image: curlimages/curl:7.83.0
      name: curl
      command: [ "bin/sh", "-c" ]
      args:
        - |
          while true; do 
            curl -I nginx-web.default.svc.cluster.local:80;
            sleep 1;
          done 
  dnsPolicy: ClusterFirst
  restartPolicy: Always
